### ISSUE TITLE
Warnings: nil value is invalid

### ISSUE THREAD

**Issue by seagle0128** [doomemacs/themes#753]
### Theme(s)

All themes (base)

### What were you expecting?

No warnings

### What actually happened?

In recent 29.1, these warnings come out.

```
Warning: setting attribute ‘:background’ of face ‘ivy-minibuffer-match-face-1’: nil value is invalid, use ‘unspecified’ instead.
...
```

### Steps to reproduce

1. Installed doom-themes.
2. Load doom-one theme.

### Operating system

All

### Emacs version

29.0.50

### Installed commit of doom-themes

latest

**Comment by elken** [comment]
Think this is related to https://github.com/emacs-mirror/emacs/commit/d0a66f3

AFAIU I don't think we're planning to support HEAD until things start to stabilize a bit.

**Comment by seagle0128** [comment]
Make sense...

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by Ethanlinyf** [comment]
I also still have the same issue: 

Warning: setting attribute ‘:background’ of face ‘font-lock-comment-face’: nil value is invalid, use ‘unspecified’ instead.

emacs-plus@29 on MacBook Pro 2021 with macOS, Ventura 13.1

**Comment by seagle0128** [comment]
I think this may cause the issue. e.g.

```elisp
((font-lock-comment-face &override) :background (if doom-feather-light-brighter-comments base0) :italic t)
```

**Comment by BobenHome** [comment]
> Hi @hlissner I still got this error:
> 
> ```
> Warning: setting attribute ‘:background’ of face ‘font-lock-comment-face’: nil value is invalid, use ‘unspecified’ instead.
> ```

How did you fix it later?

**Comment by hlissner** [comment]
I've slowly been stomping out the lingering `nil`'s in our themes. Though there may be a couple more, I *think* I can consider this issue mostly resolved for now. Feel free to follow up here if you find an issue that still emits this warning, however.
